### ISSUE TITLE
Bot Engine integration

### ISSUE THREAD

**Issue by patapizza** [wit-ai/wit-ios-sdk#64]
There is no support for the new [Converse API](https://wit.ai/docs/http/20160330#converse-link).

**Comment by jasonhotsauce** [comment]
Not sure if anyone is working on this already, if not, I am interested in giving it a try. 🍺 

Awesome product BTW. 🍻

**Comment by hactar** [comment]
Made any progress @jasonhotsauce ? I'd also take a stab at this, but does the /speech part of the API support converse yet? The documentation states intents... Also I'd need #69 merged, and to allow it to work with my app, the migration tool for old intent based apps needs to be in place...

**Comment by jasonhotsauce** [comment]
@hactar I haven't started working on it since no one from Wit responded and I don't wanna do duplicate works if someone has already been working on it. 
But I can put up a quick PR this weekend. 😄

**Comment by l5t** [comment]
So sorry for the late reply. We haven't started on it and won't have time in the next few weeks. So please go ahead ;-)

**Comment by hactar** [comment]
@jasonhotsauce Cool!

@patapizza @l5t Any chance you guys could accept #69 ? Would probably be better if @jasonhotsauce's changes would be based off that...

**Comment by jasonhotsauce** [comment]
@hactar @patapizza @l5t After taking a deeper look in the SDK. I think it will be good to clean up the SDK first, then create the `Converse` support on top of that. Otherwise the complexity will be grown and harder to clean up later. I purpose the following:
1. Further fixing retain cycles. There are more. 😈 
2. Decompose components. 
3. Instead of returning raw data, returns objects. (Optional, not sure if I have time to finish this)
4. Replace `NSURLConnection` to `NSURLSession`
5. Create some more tests. 
We can talk more about this, maybe collaborate on some of the topics. 🍻

**Comment by hactar** [comment]
Converse Endpoint has been added, however only for interpreting NSStrings, I'm working on adding the speech recognition part via iOS 10 speech recognition to be used with the converse endpoint.

**Comment by hactar** [comment]
Closing this, 4.2.0 adds the converse endpoint for both strings and speech recognition for iOS 10+.
